### ISSUE TITLE
Generate Canonical Image URLs

### ISSUE THREAD

**Issue by KazWolfe** [goatcorp/Plogon#68]
Plogon should generate its manifest files such that it overwrites any developer-provided `IconUrl` or `ImageUrls` with the images present in D17. This would allow Dalamud proper to simplify its icon fetching code to only handle a single case and always load images from a remote with no consideration about third-party status.

As a secondary consideration, plugin developers should be allowed to specify images with arbitrary names for the preview/marketing images, meaning a schema change to the TOML would be required. Example:

```toml
[plugin]
repository = "https://github.com/PluginDev/MyAwesomePlugin.git"
commit = "8ebf601f8b808c32b8d2fb570c2e0fbdbb388add"
owners = [
    "PluginDev",
]
project_path = "MyAwesomePlugin"
image_paths = [
    "images/marketing1.png",
    "images/marketing2.png",
    "images/screenshot-ui.png"
]
icon_path = "images/icon.png"
```

All images would need to be committed to D17, allowing updates without plugin version bumps.
